site_name: pytango-moenchZmqServer
theme:
    name: material

watch:
    - .
plugins:
    - search
    - mkdocstrings
    - mermaid2
    - glightbox

nav:
    - Home: index.md
    - Installation: installation.md
    - Coding guideline: guideline.md
    - Detector reference: detector.md
    - slsDetectorGroup reference: original_software.md
    - Code reference: reference.md

markdown_extensions:
    # Python Markdown
    - abbr
    - attr_list
    - toc:
          permalink: true
          toc_depth: "2-6"

    # Python Markdown Extensions
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.progressbar
    - pymdownx.extra
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:mermaid2.fence_mermaid

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
