name: Python Package using Conda

on:
  release
  
jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build-env
          python-version: '3.10'
          channels: conda-forge
          allow-softlinks: true
          channel-priority: strict
          add-pip-as-python-dependency: true
          conda-build-version: '0.10.0'
          add-anaconda-token: ${{ secrets.ANACONDA_TOKEN }}
      - name: running conda commands
        run: |
          conda config --set anaconda_upload yes
          conda build .conda
